### ISSUE TITLE
Error: -n is required. See --help for help.

### ISSUE THREAD

**Issue by hyber-code** [devilbox/cert-gen#16]
I took the example commands and first used ca-gen, after replacing example data with my dummy data everything went fine , i got ca.crt and ca.key.

secondly, i used cert-gen and used the ca.crt and ca.key generated in the previous command and i am getting the following error

COMMAND
```
cert-gen -v -c XX -s XXXX -l XXXX -o XXXX -u XXXX \ -n XXXX -e XX@XXX.XX \ -a '*.XX.net,*.www.XX.net' \ -i '10.0.0.1' \ ca.key \ ca.crt \ ac.key \ ac.csr \ ac.crt
```

ERROR
```
Error: -n is required. See --help for help.
```

**Comment by cytopia** [comment]
@hyber-code 
```bash
USAGE: cert-gen -n CN [-kdcsloueav] <ca-key> <ca-crt> <key> <csr> <crt>
       cert-gen --help
       cert-gen --version

Required arguments
  -n CN       Common Name
```

You need to use `-n` to specify a common name, which is required. Use the first value from `-a`

You can also see this in the README.md in the example section: https://github.com/devilbox/cert-gen#execute-cert-gen
