### ISSUE TITLE
Error Loading extension section v3_ca

### ISSUE THREAD

**Issue by theogravity** [devilbox/cert-gen#9]
Hi, I'm trying to create a ca using `ca-gen`, and filled out the available options:

```
$ ca-gen -n int -k 2048 -d 1024 -c US -s California -l "San Jose" -o "..." -u "..." -e "..." root.key root.crt
```

I get the error:

`Error Loading extension section v3_ca`

OS: Mac OS X High Sierra
openssl version: LibreSSL 2.2.7 (I think this comes with the OS X install)

**Comment by theogravity** [comment]
Ah, OS X does not include the `v3_ca` extension. This post details how to fix that:

https://github.com/jetstack/cert-manager/issues/279

**Comment by cytopia** [comment]
@theogravity thanks for the heads-ups
